Added index_image_resolved attribute in IIB response
release-engineering/iiblib pull request #45
Opened 2021-02-17 12:15 UTC by midnightercz

2021-02-17 15:05 UTC, querti approved these changes

2021-03-02 11:42 UTC, pbortlov commented
@midnightercz I think we miss index_image_resolved at merge-index-image model

2021-03-02 11:45 UTC, pbortlov requested changes
do we miss index_image_resolved in MergeIndexImageModel? Or we don't need it there? @midnightercz

2021-03-02 17:21 UTC, midnightercz commented
> do we miss index_image_resolved in MergeIndexImageModel? Or we don't need it there? @midnightercz

We don't need it there (so far)

2021-03-02 17:22 UTC, merged