Add functionality of IIB create-empty-index endpoint
release-engineering/iiblib pull request #47
Opened 2021-06-24 09:50 UTC by pbortlov

2021-06-25 12:33 UTC, lipoja submitted a review, later dismissed

2021-06-25 19:35 UTC, chandwanitulsi submitted a review, later dismissed

2021-06-28 15:52 UTC, midnightercz requested changes

2021-06-28 15:52 UTC, midnightercz commented on iiblib/iib_build_details_model.py
> +        binary_image (str)
from_index is not documented

2021-06-29 08:37 UTC, pbortlov commented on iiblib/iib_build_details_model.py
> +        binary_image (str)
thanks

2021-06-29 09:35 UTC, lipoja submitted a review, later dismissed

2021-06-29 10:19 UTC, querti submitted a review, later dismissed

2021-06-29 10:20 UTC, midnightercz submitted a review, later dismissed

2021-07-12 11:11 UTC, querti approved these changes

2021-07-12 12:17 UTC, midnightercz approved these changes

2021-07-12 12:19 UTC, lipoja approved these changes

2021-07-12 12:21 UTC, merged