Added build_tags attribute support
release-engineering/iiblib pull request #50
Opened 2021-10-06 11:51 UTC by midnightercz

2021-10-11 20:15 UTC, neithere commented on tests/test_iib_client.py
> +                build_tags=["extra-tag1"],
Shouldn't this be reflected in the result? We are comparing it to a model instance based on the fixture where `build_tags` is `["v4.5-2020-10-10"]`.

2021-10-18 15:27 UTC, chandwanitulsi commented on tests/test_iib_build_details_model.py
> +        "build_tags": [],
Should we have 2 build_tags in this json?

2021-11-02 14:45 UTC, querti requested changes

2021-11-02 14:45 UTC, querti commented on iiblib/iib_build_details_model.py
> -        "bundles",
Should this be removed?

2021-11-03 13:54 UTC, midnightercz commented on iiblib/iib_build_details_model.py
> -        "bundles",
it's no removed, just relocated to 226

2021-11-03 15:46 UTC, querti approved these changes

2021-11-04 07:35 UTC, merged